# Generated by Django 4.0.5 on 2022-06-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_id', models.CharField(blank=True, max_length=250)),
                ('email', models.EmailField(blank=True, max_length=100, unique=True)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField()),
            ],
            options={
                'ordering': ['date_add'],
            },
        ),
        migrations.CreateModel(
            name='keepemail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, unique=True)),
            ],
        ),
    ]
